### ISSUE TITLE
Help accessing medicationReference

### ISSUE THREAD

**Issue by patagoniacode** [apple/FHIRModels#12]
Hi again!

I'm having some issues accessing medicationReference on MedicationRequest.

## JSON snippet

```
{
         "resourceType": "MedicationRequest",
         "medicationReference":{
            "display": "Tylenol PM", // THIS IS THE VALUE I WOULD LIKE TO GET
            "reference": "#med0309"
         }
}
```

## This is what I've tried:

The MedicationRequest resource is already in a constant called medicationRequest.

```
import ModelsR4

let display = medicationRequest.medicationReference?.display?.value.string // Value of type 'MedicationRequest' has no member 'medicationReference'
```

I would really appreciate your help.

Thanks!

**Comment by p2-apple** [comment]
Try to use Xcode's autocomplete. `medicationReference` and `medicationCodeableConcept` are mutually exclusive, something sometimes called "value-x", so it's an enum that you can access using `.medication`:

```swift
let med = try decoder.decode(MedicationStatement.self, from: data)
if case .reference(let ref) = med.medication {
    print("--> medication reference display: \(ref.display ?? "{nil}")")
} else if case .codeableConcept(let cc) = med.medication {
    print("--> medication codeable concept text: \(cc.text ?? "{nil}")")
    // Note you should also look at `cc.coding`
}
```

Note that you're not guaranteed that `display` is actually present so you would need to resolve the `reference` and pull some display name from the contained `Medication` resource.

**Comment by patagoniacode** [comment]
@p2-apple, now I see they are mutually exclusive.
Thank you for your help!

**Comment by p2-apple** [comment]
Sure! Let's leave this open so I can actually document this.

**Comment by patagoniacode** [comment]
Great!
