### ISSUE TITLE
Swift compiler warning

### ISSUE THREAD

**Issue by patagoniacode** [apple/FHIRModels#15]
Hi!

I hope you are all in good health.

I'm getting the following warning:

```
Swift Compiler Warning
'self' refers to the method 'ExampleDiagnosisTypeCodes.self', which may be unexpected
Use 'ExampleDiagnosisTypeCodes.self' to silence this warning
```

I would really appreciate your help.
Thanks

<img width="670" alt="Swift compiler warning" src="https://user-images.githubusercontent.com/72701635/158658869-1a08cc11-b0b5-409e-9517-f7a5de2bc7ba.png">
!

**Comment by p2-apple** [comment]
This happens because the enum `ExampleDiagnosisTypeCodes` generates a case `self`. We use backticks to protect it but it appears that may no longer be working as expected.
