### ISSUE TITLE
STU3 FHIR (1.9) compatibility

### ISSUE THREAD

**Issue by martinmitrevski** [apple/FHIRModels#2]
Hi, 

Thanks for providing this package. I have a question about STU3 FHIR (1.9) compatibility. 

As far as I can see, the supported FHIR models are DSTU2, R4 and build. Does this mean that if I have to use STU3, I can't use this package?

Or is some of the supported versions compatible with STU3?

Thanks for any hints.

Martin

**Comment by p2-apple** [comment]
Hang tight!

(1.9 was released as 3.0 in the end)

**Comment by p2-apple** [comment]
STU-3 models have been added in `0.2.0`.

**Comment by martinmitrevski** [comment]
Thanks!
