### ISSUE TITLE
Encoding Observation.EffectiveX to JSON

### ISSUE THREAD

**Issue by nihebe** [apple/FHIRModels#6]
Hi,

I'm generating FHIR resources with FHIRModels using the native Swift JSONEncoder from Foundation. It works quite well so far, but I found a problem with the `EffectiveX` enum in `Observation`: Even though a valid `FHIRPrimitive<DateTime>` is set in the Observation, the generated JSON just contains the date (e.g. `"effectiveDateTime":"2020-11-13"`).

Here's a _(not so) minimal_ working example:
```
import Foundation
import ModelsR4

class FHIRtest {
    
    func test() {
        let frequency = Int.random(in: 50...160)
        let date = Date(timeInterval: Double.random(in: -99...99), since: Date())
        
        print("\(buildHeartrateObservation(frequency: frequency, time: date))")
    }
    
    func buildHeartrateObservation(frequency: Int, time: Date) -> String {
        // Create Coding
        let coding = Coding()
        coding.system = "http://loinc.org"
        coding.code = "8867-4"
        coding.display = "Heart Rate"
        
        // Create Codable from Coding
        let codable = CodeableConcept(coding: [Coding]())
        codable.coding?.append(coding)
        
        // Create observeration (needs codable + status, as they are mandatory)
        let observation = Observation(code: codable, status: ObservationStatus.final.asPrimitive())
        
        // Read DateTime of measurement and set as effective (Date/Time)
        let fhirDate: FHIRDate = try! FHIRDate(date: time)
        let fhirTime: FHIRTime = try! FHIRTime(date: time)
        let fhirDateTime = DateTime(date: fhirDate, time: fhirTime)
        let primitiveDateTime = FHIRPrimitive<DateTime>(fhirDateTime, id: nil, extension: nil)
        observation.effective = Observation.EffectiveX.dateTime(primitiveDateTime)
        
        // Add value quantity
        let fhirDecimalValue = FHIRDecimal(Decimal(frequency))
        let primitiveDecimal = FHIRPrimitive<FHIRDecimal>(fhirDecimalValue, id: nil, extension: nil)
        let fhirQuantity = Quantity(code: "/min", comparator: nil, extension: nil, id: nil, system: "http://unitsofmeasure.org", unit: "beats/minute", value: primitiveDecimal)
        observation.value = Observation.ValueX.quantity(fhirQuantity)
        
        // Serialize the Observation from Data to JSON String
        let observationAsData: Data?
        do {
            observationAsData = try JSONEncoder().encode(observation)
        } catch let error {
            print("Error while encoding heartrate as Observation resource: \(error.localizedDescription)")
            observationAsData = nil
        }
        
        // Done - return the Observation
        return String(data: observationAsData ?? Data(), encoding: .utf8) ?? "oops.."
    }
}
```

This leads to a serialized bundle like this:
```
{
   "status":"final",
   "effectiveDateTime":"2020-11-13",
   "code":{
      "coding":[
         {
            "display":"Heart Rate",
            "system":"http:\/\/loinc.org",
            "code":"8867-4"
         }
      ]
   },
   "valueQuantity":{
      "code":"\/min",
      "system":"http:\/\/unitsofmeasure.org",
      "value":56,
      "unit":"beats\/minute"
   },
   "resourceType":"Observation"
}
```

I think `JSONEncoder().encode()` is not capable of handling the `EffectiveX` enum with associated values.
I think this would be desirable, as it is the straight forward way to serialize FHIR resources in an iOS environment.
Which workaround do you recommend and do you see any chance for improvement here?

Cheers,
Nils

**Comment by p2-apple** [comment]
Hey! The issue is that you're not providing a Time Zone when you add the time, and since it's invalid to specify time but not a timezone `DateTime` will just ignore the time. We will improve that to log a warning so you're aware.

Instead of combining your custom FHIRDate & FHIRTime into DateTime, you can just use `try DateTime(date: {your NSDate})` directly and it will work.

**Comment by nihebe** [comment]
Hey,

thanks a lot, that helps. Somehow I have overseen the `DateTime(date:)` constructor, even though I found it for `FHIRDate` and `FHIRtime`. 🤦🏼‍♂️
The warning would be a highly appreciated improvement here.

Apart from that specific case: The readme is focussed very much on deserialization of FHIR resources. Would a pull request for the readme with a new example of creating an observation bundle + it's JSON serialization be of interest?

**Comment by p2-apple** [comment]
We'll need to update the README indeed, yes (see also #1). At this time we cannot accept PRs I'm afraid.

**Comment by nihebe** [comment]
I feel like it's a good fit to this topic and not worth a new issue, thus I comment again on this one.

Using the proposed constructor `DateTime(date:)` will also include milliseconds from the date provided. This leads to a serialization like this one: `2020-11-17T17:22:50,841586947+01:00`. However, FHIR [dateTime specification](https://www.hl7.org/fhir/datatypes.html#dateTime) only allows a `.` for separation of milliseconds.

I created the date as proposed, with `time` being a native `Date` from Foundation.
```
let fhirDateTime = try! DateTime(date: time)
let primitiveDateTime = FHIRPrimitive<DateTime>(fhirDateTime, id: nil, extension: nil)
observation.effective = Observation.EffectiveX.dateTime(primitiveDateTime)
```

Did I miss something, or is there an error with the serialization?
