### ISSUE TITLE
Need some help accessing extensions

### ISSUE THREAD

**Issue by patagoniacode** [apple/FHIRModels#9]
# Need some help accessing extensions
Hi!

First of all, congratulations for the excellent work you are doing with this library.
It's really useful for handling FHIR data.

I think this could be a very basic question, but currently I'm having some issues accessing extensions.

In the Patient resource extract listed below, what is the right way for accessing the "humanname-mothers-family" extension?

let mothersFamilyName = ... // This value should be "JOHNSON"

I would really appreciate your help.
Thanks!

## Part of a Patient resource JSON

```
{
    "resourceType": "Patient",
    "id": "2429563849",
    "name": [
        {
            "use": "official",
            "family": "SMITH",
            "_family": {
                "extension": [
                    {
                        "url": "http://hl7.org/fhir/StructureDefinition/humanname-mothers-family",
                        "stringValue": "JOHNSON" // THIS IS THE VALUE I'M TRYING TO GET
                    }
                ]
            },
            "given": [
                "JOHN"
            ]
        }
    ]
}
```

**Comment by p2-apple** [comment]
Yes indeed, it's still on my bucket list to improve documentation, as called out in #1 . Does this comment help you get at the extension?

https://github.com/apple/FHIRModels/issues/1#issuecomment-652106332

**Comment by patagoniacode** [comment]
Hi Pascal, thank you for your answer.

I read the suggested comment, but still cannot access the extension.
This is what I wrote:

## The following code returns nil and not the mother's family name
```
extension Patient {
    var mothersFamily: String? {
        guard let mothersFamilyExtension = self.extension?.first(where: { $0.url.value == "http://hl7.org/fhir/StructureDefinition/humanname-mothers-family" }) else { return nil }
        if case .string(let mothersFamily) = mothersFamilyExtension.value {
            return mothersFamily.value?.string
        } else {
            return nil
        }
    }
}
```

What am I doing wrong?
Thanks!

**Comment by drdavec** [comment]
Do you have a sample Patient JSON snippet that you are attempting to parse?  That would help debugging.  A similar standard FHIR extension has a different URI than you are using:
http://hl7.org/fhir/R4/extension-patient-mothersmaidenname.html

The extension URI you are using suggests that the value might contain a HumanName datatype instead of a string?  You must retrieve the appropriate corresponding data type from an extension value.

Hope this helps!
  Dave Carlson

**Comment by patagoniacode** [comment]
Hi Dave, thank you for taking the time to answer!

### This is a JSON snippet of the Patient resource:

```
{
    "resourceType": "Patient",
    "id": "2429563849",
    "name": [
        {
            "use": "official",
            "family": "SMITH",
            "_family": {
                "extension": [
                    {
                        "url": "http://hl7.org/fhir/StructureDefinition/humanname-mothers-family",
                        "stringValue": "JOHNSON" // THIS IS THE VALUE I'M TRYING TO GET
                    }
                ]
            },
            "given": [
                "JOHN"
            ]
        }
    ]
}
```

### Regarding  the previews code, this is the point where it exits:

```
import ModelsR4

extension Practitioner {
    var mothersFamily: String? {
        guard let mothersFamilyExtension = self.extension?.first(where: { $0.url.value == "http://hl7.org/fhir/StructureDefinition/humanname-mothers-family" }) else {
            print("THIS LINES IS PRINTED")
            return nil
        }
        if case .string(let mothersFamily) = mothersFamilyExtension.value {
            return mothersFamily.value?.string
        } else {
            return nil
        }
    }
}
```

Thanks again for your help!

**Comment by drdavec** [comment]
A FHIR extension can appear on any element within a Resource structure.  In
your example, the extension is on the 'family' element *within* a HumanName
datatype, within the Patient resource.  You are attempting to find this
extension on the Patient root structure, and it's not located there in your
example.

I would need to play around with the Swift code to make this work.  Your
extension may need to be on the FHIRModels String datatype, not on
Patient.  But it might be better to traverse the Patient name -> HumanName
-> family and then retrieve the extension from that nested element.

Dave

**Comment by p2-apple** [comment]
You are close, and together with @drdavec 's suggestions the solution is something like:

- Fix `stringValue` to `valueString` in your sample JSON
- Put the utility method on `FHIRPrimitive` instead

```swift
extension FHIRPrimitive {
    
    var mothersFamilyName: String? {
        guard let mothersFamilyExtension = extensions(for: "http://hl7.org/fhir/StructureDefinition/humanname-mothers-family").first else {
            return nil
        }
        if case .string(let str) = mothersFamilyExtension.value {
            return str.value?.string
        }
        // Not a `valueString`
        return nil
    }
}
```

Running the code:

```swift
import ModelsR4

let string = """
    {
        "resourceType": "Patient",
        "id": "2429563849",
        "name": [
            {
                "use": "official",
                "family": "SMITH",
                "_family": {
                    "extension": [
                        {
                            "url": "http://hl7.org/fhir/StructureDefinition/humanname-mothers-family",
                            "valueString": "JOHNSON"
                        }
                    ]
                },
                "given": [
                    "JOHN"
                ]
            }
        ]
    }
    """
guard let data = string.data(using: .utf8) else {
    throw ...
}

let decoder = JSONDecoder()
let patient = try decoder.decode(Patient.self, from: data)
for name in patient.name ?? [] {
    print("family: \(name.family?.value?.string ?? "{nil}"), mother's family: \(name.family?.mothersFamilyName ?? "{nil}")")
}
// prints: "family: SMITH, mother's family: JOHNSON"
```

**Comment by patagoniacode** [comment]
Dear Dave and Pascal, now it works perfectly!
Thank you very much for taking the time to help me.
Greetings!

**Comment by p2-apple** [comment]
I've just pushed the above example to https://github.com/apple/FHIRModels/blob/main/HowTo/Extensions.md
